#count:
#  measure_module: funtool_common_processes.group_measures.default
#  measure_function: count
#  analysis_selectors: !!null
#  grouping_selectors: 
#    - all
#    - projects_directory
#    - total_sprites
#  parameters: !!null
#  
#average_doIf:
#  measure_module: funtool_common_processes.group_measures.default
#  measure_function: average
#  analysis_selectors: !!null
#  grouping_selectors: 
#    - all
#    - projects_directory
#  parameters:
#    average_type: measures
#    average_value: doIf_count
